### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by cismarine** [bessarabov/mac2mqtt#7]
Hi, I am not a Go person.
Getting the following error while running $ go run mac2mqtt.go

`mac2mqtt % go run mac2mqtt.go
package command-line-arguments
	imports gopkg.in/yaml.v2
	imports gopkg.in/yaml.v2: import cycle not allowed`

**Comment by christoph-morrison** [comment]
Please show your `go.mod` file.

**Comment by callumgare** [comment]
Check out this PR if you'd like to run/build the source: https://github.com/bessarabov/mac2mqtt/pull/9

**Comment by bessarabov** [comment]
I'm pretty sure that you have faced this problem because there was were no `go.mod`  and no `go.sum` files in the reposity. Now this is fixed, and the files are present in this repo (done in https://github.com/bessarabov/mac2mqtt/commit/ec0bbea53a63f78133b707036d2a06d1630c5582 )

But besides that now there is also a pre-complived binaries that you can just take and use. There is a GitHub Action that auto builds project and put complied versiosn to the Releases Page. The first release with them is https://github.com/bessarabov/mac2mqtt/releases/tag/1.4.0

I've also added this info to README.md file — (done in commit https://github.com/bessarabov/mac2mqtt/commit/c00296689256e870b18e22ff7dc1a23473f97848 )

I believe there's no point in keeping this issue open right now, so I'm closing it.
